### ISSUE TITLE
i18n support for webcomponents

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/search-a-licious#161]
### What
- Do we need to support translations in webcomponents ?
- If yes, integrate an existing library to handle that (the most standard one).
- If no (because it can be done by the integrator with his framework of choice), just add documentation on how to do it.

**Comment by alexgarel** [comment]
@alexfauquette, @VaiTon I would appreciate your insights on that (if you have some ;-))

**Comment by alexfauquette** [comment]
What I usually see is a `localeText` object:
- [AGgrid](https://www.ag-grid.com/javascript-data-grid/localisation/)
- [MUI](https://mui.com/x/react-date-pickers/localization/)

The object can either be set globally (defined once for the entire app) or locally (defined for only one component

Its value can either be string for fixed translation. For example: { nextPage: "Page suivante" } or functions { currentPage: (pageNumber) => `page numéro ${pageNumber}` }

**Comment by alexgarel** [comment]
Being compatible with crowdin is useful, see https://support.crowdin.com/supported-formats/
