### ISSUE TITLE
Write API documentation

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/search-a-licious#21]
We should document the API.

Writing an OpenAPI documentation should be the choice.

We also generally follow https://diataxis.fr/ schema. So OpenAPI doc should go in docs/reference.

**Comment by raphael0202** [comment]
API can be generated very easily with fastapi: https://fastapi.tiangolo.com/tutorial/first-steps/?h=openapi#interactive-api-docs

**Comment by raphael0202** [comment]
Done, all endpoints are documented now using FastAPI.
