### ISSUE TITLE
Use logging instead of print

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/search-a-licious#24]
We use print in the current code to display message.

This is not a good practice:
- if you don't add flush=True, message get printed at random moment
- we can't add debug print and decide to ignore them easily
- we won't be able to send log errors to sentry if we set it up

**Comment by alexgarel** [comment]
We need to have a way to setup logging (but BasicConfig should do as a first approach).

**Comment by dheerajdlalwani** [comment]
Hey! This seems like an interesting issue for someone like me who's trying to learn and understand about logging. Do you mind if I take this issue up? Also, I may need some assistance.

**Comment by alexgarel** [comment]
Be welcome @dheerajdlalwani !

**Comment by raphael0202** [comment]
Done!
