### ISSUE TITLE
Change CORS headers to allow JS queries

### ISSUE THREAD

**Issue by dq18** [openfoodfacts/search-a-licious#80]
Open-prices will soon have to query this API. Either allow origin for prices.openfoodfacts.[org, net] or allow_header=["*"]

**Comment by alexfauquette** [comment]
Upvoted this issue. The implementation is ready, but even from hunger.openfoodfacts.org it returns a CORS

https://hunger.openfoodfacts.org/logos/search?type=brand

**Comment by alexgarel** [comment]
I think we can go for allow_header=["*"] as it's intended for public use.

**Comment by raphodn** [comment]
Hi ! Doesn't seem to work :(

I get CORS error when calling the API in my JS code from:
- http://localhost:5173
- https://prices.openfoodfacts.net

**Comment by RickWong** [comment]
Hi @Kout95 @alexgarel — I opened a PR to set the ALLOWED_ORIGINS for development to strictly localhost, and for staging/production to wildcard. That last part will thus allow Progressive Web Apps like prices.openfoodfacts.net (and others) to invoke searches.

**Comment by raphodn** [comment]
this is still an issue 👀 

<img width="415" height="397" alt="Image" src="https://github.com/user-attachments/assets/98f893b3-a90d-4095-b72e-98bcb5251b6d" />

**Comment by RickWong** [comment]
Can someone release version 1.5.0 (see PR) to production?
