### ISSUE TITLE
Use Docker V2 recommended syntax in Makefile

### ISSUE THREAD

**Issue by amottier** [openfoodfacts/search-a-licious#89]
### Problem
With recent version of Docker, Docker Compose is part of docker CLI and can be run using `docker compose` instead of `docker-compose`.
With my setup on Debian using Docker package repository the `docker-compose` command is not available (in remains available for user of Docker desktop according to [Migrate to Compose V2](https://docs.docker.com/compose/migrate/) documentation).
Updating to the new syntax would ease the build of Docker image in up to date environment.

### Proposed solution
Replace `docker-compose` by `docker compose`.

**Comment by alexgarel** [comment]
Hi @amottier, feel free to propose a PR !

**Comment by amottier** [comment]
This issue has been fixed by 003739c5b8ec7b93006555feff4375a43677f1dd
